[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
lib_deps =
    bodmer/TFT_eSPI@^2.5.43
    bblanchon/ArduinoJson@^7.0.0
build_flags =
    ; Species: 0=capybara 1=duck 2=goose 3=blob 4=cat 5=dragon 6=octopus 7=owl
    ;          8=penguin 9=turtle 10=snail 11=ghost 12=axolotl 13=cactus 14=robot
    ;          15=rabbit 16=mushroom 17=chonk
    -DDEFAULT_SPECIES=3
    -DSESSION_CAP=50000
    -DWEEK_CAP=1000000
    -DUSER_SETUP_LOADED=1
    -DGC9A01_DRIVER=1
    -DUSE_FSPI_PORT
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=240
    -DTFT_MOSI=11
    -DTFT_SCLK=10
    -DTFT_CS=9
    -DTFT_DC=8
    -DTFT_RST=12
    -DTFT_BL=40
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DLOAD_FONT4=1
    -DSPI_FREQUENCY=80000000
    -DSPI_READ_FREQUENCY=20000000
monitor_speed = 115200
